[package]
name = "cli-prompts"
version = "0.1.0"
edition = "2021"
author = "Melesar"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23"
